# Generated by Django 3.1.1 on 2020-09-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carwash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('foundation_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('car_body', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Cabriolet', 'Cabriolet'), ('Pickup', 'Pickup'), ('Fourgon', 'Fourgon')], max_length=10)),
                ('interior_cleaning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('order_date', models.DateField()),
                ('carwash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carwash')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
