# Generated by Django 3.1.1 on 2020-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200907_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carwashes',
            field=models.ManyToManyField(through='main.Order', to='main.Carwash'),
        ),
    ]
