# Generated by Django 3.1.1 on 2020-09-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_carwashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='photo',
            field=models.ImageField(null=True, upload_to='CarwashImages'),
        ),
    ]
