# Generated by Django 3.1.1 on 2020-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200915_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='CarwashImages'),
        ),
    ]
