# Generated by Django 3.1.1 on 2020-10-03 16:44

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200915_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={}, null=True),
        ),
    ]
