# Generated by Django 3.1.1 on 2020-10-11 11:56

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carwash_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carwash',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (30.522366336674224, 50.45084688302083)}, null=True),
        ),
    ]
