# Generated by Django 3.1.1 on 2020-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201011_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
        migrations.AddField(
            model_name='customer',
            name='name_surname',
            field=models.CharField(default='Іван Іванов', max_length=40),
            preserve_default=False,
        ),
    ]
